# Github action to deploy functions from firebase/functions directory
name: Deploy Firebase Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          working-directory: firebase/functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        working-directory: firebase/functions

      - name: Install Dependencies
        run: npm install
        working-directory: firebase/functions

      - name: Deploy Firebase Functions
        run: npm run deploy
        working-directory: firebase/functions
